---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.09.2020 11:50
---
---
--Настройки
HeartAbility=FourCC("A000") --любая способность
HeartAbilityUnits={}
TIMER_PERIOD = 0.03125

do --Инициализация
	TimerStart(CreateTimer(), 1, false, function()
		perebor = CreateGroup()
		TimerStart(CreateTimer(), 1, true, function()
			FindButchers() -- каждую секунду ищем нового мясника и проверяем не попал ли он в систему
		end)
	end)
end

function FindButchers()
	local  e=nil
	GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
	while true do
		e = FirstOfGroup(perebor)

		if e == nil then break end
		if UnitAlive(e) then
			if  GetUnitAbilityLevel(e,HeartAbility)>0 and not HeartAbilityUnits[GetHandleId(e)] then
				HeartAbilityUnits[GetHandleId(e)]=e
				HearBit(e)
				--print("Юнит добавлен")
			end
		else
			HeartAbilityUnits[GetHandleId(e)]=nil
			--print("Юнит удалён")
		end
		GroupRemoveUnit(perebor,e)
	end
end

function HearBit(hero)
	local healAmount=50
	local loosingHP=100-(GetUnitState(hero,UNIT_STATE_LIFE)/BlzGetUnitMaxHP(hero)*100)
	local nextBit=3-loosingHP*.02
	ScalingIconTimed(BlzGetAbilityIcon(HeartAbility), 0.2, 5, healAmount,hero) -- 5 определяет позицию иконки 1.1
	local tl = Location(GetUnitX(hero),GetUnitY(hero))
	PlaySoundAtPointBJ(soundBit, 100, tl, 0)
	--print("playsoind")
	RemoveLocation(tl)
	--print("Тут лечим юнита "..loosingHP)
	HealUnit(hero,healAmount)
	TimerStart(CreateTimer(), nextBit, false, function()
		if UnitAlive(hero) then
			HearBit(hero)
		else
			HeartAbilityUnits[GetHandleId(hero)]=nil
		end
	end)
end

--ScalingIconTimed(BlzGetAbilityIcon(SpellIDS), 0.2, 5, data.bonusCD,caster)
function ScalingIconTimed(FrameTexture, secShow, posButton, text,hero)
	if not IsUnitSelected(hero,GetOwningPlayer(hero))  then
		return
	end
	local size = 0
	local sec = 0
	local i = 1
	local turn = true
	local next = 0.039
	local fh = BlzCreateFrameByType("BACKDROP", "FaceButtonIcon", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetSize(fh, next, next)
	BlzFrameSetTexture(fh, FrameTexture, 0, true)
	local CBPoz = BlzGetFrameByName("CommandButton_" .. posButton, 0) -- CommandButton_0
	BlzFrameSetPoint(fh, FRAMEPOINT_CENTER, CBPoz, FRAMEPOINT_CENTER, 0, 0)
	local newText = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetText(newText, text)
	BlzFrameSetPoint(newText, FRAMEPOINT_CENTER, CBPoz, FRAMEPOINT_CENTER, 0, 0)

	if not GetLocalPlayer()==GetOwningPlayer(hero) then
		BlzFrameSetVisible(fh,false)
		BlzFrameSetVisible(fh,false)
	end

	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		sec = sec + TIMER_PERIOD
		size = size + (i * 0.005)
		if sec >= secShow and turn then
			turn = false
			i = i * (-1)
		end
		if size <= 0 then
			DestroyTimer(GetExpiredTimer())
			BlzDestroyFrame(fh)
			BlzDestroyFrame(newText)
			size = 0
		end
		BlzFrameSetSize(fh, next + size, next + size)
		BlzFrameSetScale(newText, (next + size) * 50)
	end)
end

function FlyTextTag(text, textSize, x, y, z, red, green, blue, alpha, xvel, yvel, fadepoint, lifespan, player)
	local t = CreateTextTag()
	SetTextTagText(t, text, textSize)
	SetTextTagPos(t, x, y, z)
	SetTextTagColor(t, red, green, blue, alpha)
	SetTextTagVelocity(t, xvel, yvel)
	SetTextTagFadepoint(t, fadepoint)
	SetTextTagLifespan(t, lifespan)
	SetTextTagPermanent(t, false)
	if player ~= nil then
		SetTextTagVisibility(t, player == GetLocalPlayer())
	end
	return t
end
function FlyTextTagHealXY(x,y, text, player)
	return FlyTextTag(text, 0.024, x, y, 150, 88, 250, 13, 255, 0, 0.03, 1, 3, player)
end


