---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.08.2020 19:03
---

do --Инициализация
	TimerStart(CreateTimer(), 1, true, function()
			--HowChild()
	end)
end

function HowChild()
	local tip=BlzGetOriginFrame(ORIGIN_FRAME_UBERTOOLTIP, 0)
	local k=BlzFrameGetChildrenCount(tip)

	local uberchild=BlzFrameGetChild(tip,0)
	BlzFrameSetAlpha(uberchild,128)
	local k2=BlzFrameGetChildrenCount(uberchild)
	print(BlzFrameGetText(uberchild)..k2)
	--Убер чилд имеет 8 детей
	local eight={}
	for i=0,7 do
		eight[i]=BlzFrameGetChild(uberchild,i)
		BlzFrameSetAlpha(eight[i],128)
		local k3=BlzFrameGetChildrenCount(eight[i])
		print(BlzFrameGetText(eight[i]).." emp"..i.." "..k3) -- Выводит пустоту и показывает что 0 потомков
	end
end