---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.02.2021 0:06
---


do
    local InitGlobalsOrigin = InitGlobals -- записываем InitGlobals в переменную
    function InitGlobals()
        InitGlobalsOrigin() -- вызываем оригинальную InitGlobals из переменной
        TimerStart(CreateTimer(), 2, false, function()
            InitEnemyEntire()
        end)
    end
end

function InitEnemyEntire()
    local gg_trg_FFF = CreateTrigger()
    TriggerRegisterEnterRectSimple(gg_trg_FFF, GetPlayableMapRect())
    TriggerAddAction(gg_trg_FFF, function()
        local unit=GetTriggerUnit()
       -- print(GetUnitName(unit))
        if GetUnitTypeId(unit)==FourCC("nsko") then -- простые скелеты орки с молотом
            IssueTargetOrder(unit,"attack",GetRandomEnemyHero())
            JumpAI(unit)
        end
        if GetUnitTypeId(unit)==FourCC("ucs1") then -- маленький скоробей
            SinergyBug(unit)
        end
        if GetUnitTypeId(unit)==FourCC("unec") then -- некр
            NecroAttackAndArrow(unit)
        end
        if GetUnitTypeId(unit)==FourCC("uabo") then
            PudgeSlash(unit)
        end

    end)
end

function UnitAddShield(unit,amount)
    UnitAddAbility(unit,FourCC("ACmf")) --Бафф BNms
    BlzSetUnitMaxMana(unit,amount)
    SetUnitState(unit,UNIT_STATE_MANA,amount)
    if not IssueImmediateOrder(unit,"manashieldon") then
        print("Не могу активировать щит")
    end
end

function GetRandomEnemyHero()
    local table={}
    local k=1
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        if IsPlayerSlotState(Player(i), PLAYER_SLOT_STATE_PLAYING) and GetPlayerController(Player(i))==MAP_CONTROL_USER then
            local data=HERO[i]
            if UnitAlive(data.UnitHero) then
                --print("найден живой")
                table[k]=data.UnitHero
                k=k+1
            end
        end
    end
    local r=GetRandomInt(1,#table)
    return table[r]
end

function PudgeSlash(unit)
    local sec=0
    UnitAddAbility(unit,FourCC("Abun"))
    BlzSetUnitWeaponRealField(unit,UNIT_WEAPON_RF_ATTACK_BASE_COOLDOWN,0,2)
    BlzSetUnitWeaponRealField(unit,UNIT_WEAPON_RF_ATTACK_BASE_COOLDOWN,1,2)
    TimerStart(CreateTimer(), 1, true, function()
        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
        else
            local hero=GetRandomEnemyHero()
            local dist=DistanceBetweenXY(GetUnitX(unit),GetUnitY(unit),GetUnitXY(hero))
            sec=sec-1
            if dist<=400 and sec<=0 and hero then
                if not IsUnitStunned(unit) then
                    sec=5
                    --print(dist.." дистанция")
                    local angle=AngleBetweenUnits(unit,hero)
                    BlzPauseUnitEx(unit,true)
                    --SetUnitAnimation(unit,"attack")
                    --if not GR then GR=0 end
                    --GR=GR+1
                    --print(GR)
                    SetUnitAnimationByIndex(unit,2)
                    SetUnitTimeScale(unit,0.5)

                    -- CreateVisualMarkTimedXY("SystemGeneric\\Redline\\cone",1,GetUnitXY(unit))
                    local eff=AddSpecialEffect("SystemGeneric\\Redline\\cone",GetUnitXY(unit))
                    BlzSetSpecialEffectColor(eff,255,255,255)
                    BlzSetSpecialEffectZ(eff,GetTerrainZ(GetUnitXY(unit))+50)
                    BlzSetSpecialEffectYaw(eff,math.rad(GetUnitFacing(unit)))

                    local eff1=AddSpecialEffect("SystemGeneric\\Redline\\cone",GetUnitXY(unit))
                    BlzSetSpecialEffectColor(eff1,255,255,255)
                    BlzSetSpecialEffectZ(eff1,GetTerrainZ(GetUnitXY(unit))+50)
                    BlzSetSpecialEffectYaw(eff1,math.rad(GetUnitFacing(unit)))

                    local eff2=AddSpecialEffect("SystemGeneric\\Redline\\cone",GetUnitXY(unit))
                    BlzSetSpecialEffectColor(eff2,255,255,255)
                    BlzSetSpecialEffectZ(eff2,GetTerrainZ(GetUnitXY(unit))+50)
                    BlzSetSpecialEffectYaw(eff2,math.rad(GetUnitFacing(unit)))

                    BlzSetSpecialEffectMatrixScale(eff,0.5,1.5,1)
                    BlzSetSpecialEffectMatrixScale(eff1,0.5,1.5,1)
                    BlzSetSpecialEffectMatrixScale(eff2,0.5,1.5,1)

                    TimerStart(CreateTimer(), 1.5, false, function()
                        DestroyEffect(eff)
                        DestroyEffect(eff1)
                        DestroyEffect(eff2)
                        BlzSetSpecialEffectPosition(eff,OutPoint,OutPoint,0)
                        BlzSetSpecialEffectPosition(eff1,OutPoint,OutPoint,0)
                        BlzSetSpecialEffectPosition(eff2,OutPoint,OutPoint,0)
                    end)

                    TimerStart(CreateTimer(), 1, false, function()
                        -- x1, x2 - координаты проверяемой точки
                        -- x2, y2 - координаты вершины сектора
                        -- orientation - ориентация сектора в мировых координатах
                        -- width - уголовой размер сектора в градусах
                        -- radius - окружности которой принадлежит сектор
                        BlzPauseUnitEx(unit,false)
                        SetUnitTimeScale(unit,1)
                        if not IsUnitStunned(unit) then
                            normal_sound("Sound\\Units\\Combat\\MetalHeavyBashFlesh3",GetUnitXY(unit))
                            local is,_,_,all=UnitDamageArea(unit,0,GetUnitX(unit),GetUnitY(unit),400)
                            for i=1,#all do
                                local x,y=GetUnitXY(all[i])

                                if IsPointInSector(x,y,GetUnitX(unit),GetUnitY(unit),GetUnitFacing(unit),60,200) then
                                    UnitDamageTarget(unit, all[i], 200, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS)
                                    --print("звук удара мясника")
                                    normal_sound("Units\\Undead\\Abomination\\AbominationYesAttack"..GetRandomInt(1,4),GetUnitXY(unit))
                                end
                            end
                        end
                    end)
                end
            else
                IssuePointOrder(unit,"move",GetUnitXY(hero))
            end
        end
    end)
end

function NecroAttackAndArrow(unit)
    --подготовка
    UnitAddAbility(unit,FourCC("Abun"))
    IssueImmediateOrder(unit,"raisedeadon")
    TimerStart(CreateTimer(), 2, true, function()
        if not UnitAlive(unit) then
            DestroyTimer(GetTriggerUnit())
        else
            local hero=GetRandomEnemyHero()
            --local dist=DistanceBetweenXY(GetUnitX(unit),GetUnitY(unit),GetUnitXY(hero))
            if not IsUnitStunned(unit) and hero then
                if not IsUnitInRange(hero,unit,300 ) then
                    local angle=AngleBetweenUnits(unit,hero)
                    BlzPauseUnitEx(unit,true)
                    SetUnitAnimation(unit,"attack")
                    --SetUnitTimeScale(unit,0.7)
                    SetUnitFacing(unit,angle)
                    TimerStart(CreateTimer(), 0.3, false, function()
                        CreateAndForceBullet(unit,angle,20,"Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile.mdl",nil,nil,50,3000)
                        BlzPauseUnitEx(unit,false)
                    end)
                else
                    local rx=GetUnitX(unit)+GetRandomInt(-1,1)*300
                    local ry=GetUnitY(unit)+GetRandomInt(-1,1)*300
                    IssuePointOrder(unit,"move",rx,ry)
                end
            end
        end
    end)
end


Bugs=CreateGroup()
function SinergyBug(unit)

    GroupAddUnit(Bugs,unit)
    TimerStart(CreateTimer(), 1, true, function()
        if not UnitAlive(unit) then
            DestroyTimer(GetTriggerUnit())
            ForGroup(Bugs,function()
                local e=GetEnumUnit()
                IssueTargetOrder(e,"attack",GetRandomEnemyHero())
            end)
        end
    end)

end




function JumpAI(unit)
    TimerStart(CreateTimer(), 5, true, function()
        if not UnitAlive(unit) then
            DestroyTimer(GetTriggerUnit())
        else
            local hero=GetRandomEnemyHero()
            local dist=DistanceBetweenXY(GetUnitX(unit),GetUnitY(unit),GetUnitXY(hero))

            if dist>200 and dist<600 then
                if not IsUnitStunned(unit) then
                    --print(dist.." дистанция")
                    local angle=AngleBetweenUnits(unit,hero)
                    BlzPauseUnitEx(unit,true)
                    SetUnitAnimation(unit,"attack")
                    SetUnitTimeScale(unit,0.7)
                    CreateVisualMarkTimedXY("SystemGeneric\\Alarm",1,GetUnitXY(hero))
                    TimerStart(CreateTimer(), 0.5, false, function()
                        UnitAddForceSimple(unit,angle,20,dist,"forceAttack")
                    end)
                end
            end
        end
    end)
end

function CreateVisualMarkTimedXY(effModel,timed,x,y)
    local eff=AddSpecialEffect(effModel,x,y)
    BlzSetSpecialEffectColor(eff,255,0,0)
    BlzSetSpecialEffectZ(eff,GetTerrainZ(x,y)+50)
    TimerStart(CreateTimer(), timed, false, function()
        DestroyEffect(eff)
        BlzSetSpecialEffectPosition(eff,OutPoint,OutPoint,0)
    end)
end


