---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 28.02.2021 16:06
---

function LearnCurrentTalonForPlayer(pid,godName)
    if GlobalTalons[pid][godName][6].level==1 then
        print("Игрок "..GetPlayerName(Player(pid)).. " изучил талант заряды кирки, делаем дейсвие")
    end
end