---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 04.07.2020 2:23
---
Force2DTable={}
function UnitAddForceVector2D(hero,speed,angle)
	if not Force2DTable[GetHandleId(hero)] then
		--	print("оглушен первый раз")
		Force2DTable[GetHandleId(hero)]={
			Time=0,
			Timer=nil
		}
	end
	local data=Force2DTable[GetHandleId(hero)]

	TimerStart(data.Timer, TIMER_PERIOD, true, function()

	end)
end

--Старый кастрированный вариант
onForces = {}
function UnitAddForceSimple(hero, angle, speed, distance)
	-- псевдо вектор использовать только для юнитов
	local currentdistance = 0
	if onForces[GetHandleId(hero)] == nil then
		onForces[GetHandleId(hero)] = true
	end
	if not IsUnitType(hero, UNIT_TYPE_STRUCTURE) and onForces[GetHandleId(hero)]  then
		onForces[GetHandleId(hero)]=false
		TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
			currentdistance = currentdistance + speed
			--print(currentdistance)
			local x, y = GetUnitX(hero), GetUnitY(hero)
			local newX, newY = MoveX(x, speed, angle), MoveY(y, speed, angle)

			SetUnitPositionSmooth(hero, newX, newY)

			if currentdistance >= distance then
				--or (data.OnWater and data.OnTorrent==false)
				--data.IsDisabled=false
				--data.OnWater=false
				DestroyTimer(GetExpiredTimer())
				onForces[GetHandleId(hero)]=true
				--print("stop cur="..currentdistance.." dist="..distance)
			end
		end)
	end
end