---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 29.06.2020 16:21
---
function CreateAbilityToolTip(mainData,data)
	data.ToolTip=BlzCreateFrame("DemoBoxTooltip", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0)
	local size=mainData.CustomAbilities[data.HotKeyPos].SizeTooltip
	BlzFrameSetSize(data.ToolTip,0.29,0.012*size)
	--BlzFrameSetAbsPoint(data.ToolTip,FRAMEPOINT_CENTER,0.655,0.25)

	BlzFrameSetPoint(data.ToolTip, FRAMEPOINT_BOTTOM, BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), FRAMEPOINT_BOTTOM, 0.25, 0.16)

	local contaiter=BlzFrameGetChild(data.ToolTip,1)
	local title=BlzFrameGetChild(contaiter,0)
	local description=BlzFrameGetChild(contaiter,1)
	BlzFrameSetText(title,mainData.CustomAbilities[data.HotKeyPos].Name)
	BlzFrameSetText(description,mainData.CustomAbilities[data.HotKeyPos].Description)
	BlzFrameSetVisible(data.ToolTip,false)
	local k=0
	if mainData.CustomAbilities[data.HotKeyPos].ManaCost then
		BlzFrameSetText(title,mainData.CustomAbilities[data.HotKeyPos].Name.."\n    ".."|cffffff00"..mainData.CustomAbilities[data.HotKeyPos].ManaCost.."|r") -- |cffffff00TEXT|r
		--print("способность имеет ману")
		local res= BlzCreateFrameByType("BACKDROP", "Face",data.ToolTip, "", 0)
		BlzFrameSetTexture(res, "UI\\Widgets\\tooltips\\Human\\tooltipmanaicon", 0, true)
		BlzFrameSetSize(res, 0.01, 0.01)
		BlzFrameSetPoint(res, FRAMEPOINT_TOPLEFT, data.ToolTip, FRAMEPOINT_TOPLEFT, 0.005,-0.017)
		k=0.01
	end
	BlzFrameSetText(title,BlzFrameGetText(title).."\n ") --вставка сеператора
	local separator=BlzCreateFrameByType("BACKDROP", "Face",data.ToolTip, "", 0)
	BlzFrameSetTexture(separator, "UI\\Widgets\\tooltips\\Human\\horizontalseparator", 0, true)
	BlzFrameSetSize(separator, 0.28, 1/16*0.01)
	BlzFrameSetPoint(separator, FRAMEPOINT_TOPLEFT, data.ToolTip, FRAMEPOINT_TOPLEFT, 0.005,-0.02-k)
	--print(mainData.CustomAbilities[data.HotKeyPos].Name)
	--Динамическо обновление
	if mainData.CustomAbilities[data.HotKeyPos].Updatable then --Обновление текста в тултипах
		TimerStart(CreateTimer(), TIMER_PERIOD, true, function() --TODO сделать всё на 1 таймере, а не это вот всё
			local NativeString=mainData.CustomAbilities[data.HotKeyPos].Description
			NativeString =string.gsub(NativeString,'ms',math.floor(GetUnitMoveSpeed(mainData.UnitHero)))
			NativeString =string.gsub(NativeString,'ar',math.floor(BlzGetUnitWeaponRealField(mainData.UnitHero,UNIT_WEAPON_RF_ATTACK_RANGE,0)))
			NativeString =string.gsub(NativeString,'ap',math.floor(BlzGetUnitBaseDamage(mainData.UnitHero,0)))
			NativeString =string.gsub(NativeString,'as',BlzGetUnitAttackCooldown(mainData.UnitHero,0))
			BlzFrameSetText(description,NativeString)
		end)
	end

end
function ShowAbilityTooltip (mainData,data,isShow)
	if isShow then
		if GetLocalPlayer()==Player(mainData.pid) then
			--print(mainData.CustomAbilities[data.HotKeyPos].Name.." Шоу тултип вызван")
			BlzFrameSetVisible(data.ToolTip,true)
		end
	end
	return isShow
end

function HideAllToolTips(mainData)
	--print("способности скрыты")
	for i=1,12 do
		local data=mainData.FrameTable[i]
	BlzFrameSetVisible(data.ToolTip,false)
	end
end

