---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 05.05.2021 17:02
---
function SlowUnit(unit,duration)
    local x,y=GetUnitXY(unit)
    local dummy= CreateUnit(GetOwningPlayer(unit), DummyID, x, y, 0)
    UnitAddAbility(dummy,FourCC("A008"))
    UnitApplyTimedLife(dummy, FourCC('BTLF'), 2)
    if  IssueTargetOrder(dummy,"slow",unit) then
       -- print(GetUnitName(unit))
    end
    TimerStart(CreateTimer(), duration, false, function()
        UnitRemoveAbility(unit,FourCC("Bslo"))
        DestroyTimer(GetExpiredTimer())
    end)
end