---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 29.06.2020 23:06
---
cactusModel = "Doodads\\Barrens\\Plants\\Cactus\\Cactus" .. "" --0-9
function DestroyEatingCactus(mainData,data,WCD)
	mainData.StartDrawing=false
	local hero=mainData.UnitHero
	DestroyTimer(mainData.DrawingTimer)
	BlzSetSpecialEffectPosition(mainData.effDrawing, OutPoint, OutPoint, 0)
	DestroyEffect(mainData.effDrawing)
	mainData.effDrawing = nil

	--CreateCactus(mainData, x, y, r,curAngle)
	if WCD then
		--print("отмена с кд")
		--StarFrameCooldown(data,0)
		SelectUnitForPlayerSingle(hero,GetOwningPlayer(hero))
	else
	--	print("одиночный клик?")
	end
	EnableSelect(true,true)
	return WCD
end


function EatingCactus(mainData)
	--print("курсор превращается в кактус")
	local hero = mainData.UnitHero
	local lastX, lastY = GetPlayerMouseX[mainData.pid], GetPlayerMouseY[mainData.pid]
	local r = GetRandomInt(0, 9)

	mainData.effDrawing = AddSpecialEffect(cactusModel .. r, lastX, lastY)
	BlzSetSpecialEffectAlpha(mainData.effDrawing,60)
	BlzSetSpecialEffectYaw(mainData.effDrawing, math.rad(GetRandomReal(0, 360)))


	local lastDistance = 0
	local range=80
	local angleCast = AngleBetweenXY(GetUnitX(hero), GetUnitY(hero), GetPlayerMouseX[mainData.pid], GetPlayerMouseY[mainData.pid]) / bj_DEGTORAD
	local curAngle = angleCast
	local distance = DistanceBetweenXY(GetUnitX(hero), GetUnitY(hero), GetPlayerMouseX[mainData.pid], GetPlayerMouseY[mainData.pid])
	local cutDistance = distance
	local starDrawing=false
	local data=mainData.FrameTable[11]
	EnableSelect(false,false)
	SelectUnitForPlayerSingle(hero,GetOwningPlayer(hero))
	mainData.DrawingTimer=CreateTimer()


	TimerStart(mainData.DrawingTimer, TIMER_PERIOD, true, function()
		distance = DistanceBetweenXY(GetUnitX(hero), GetUnitY(hero), GetPlayerMouseX[mainData.pid], GetPlayerMouseY[mainData.pid])
		cutDistance = math.lerp(cutDistance, distance, TIMER_PERIOD * 16)
		angleCast = AngleBetweenXY(GetUnitX(hero), GetUnitY(hero), GetPlayerMouseX[mainData.pid], GetPlayerMouseY[mainData.pid]) / bj_DEGTORAD
		curAngle = lerpTheta(curAngle, angleCast, TIMER_PERIOD * 16)

		local xp, yp = GetPlayerMouseX[mainData.pid], GetPlayerMouseY[mainData.pid]
		local x, y = MoveXY(GetUnitX(hero), GetUnitY(hero), cutDistance, curAngle)
		local distanceMove = DistanceBetweenXY(xp, yp, lastX, lastY)

		if IsPointCanCreatedCactus(mainData,x,y)  then
			BlzSetSpecialEffectColor(mainData.effDrawing,255,255,255)
			BlzSetSpecialEffectAlpha(mainData.effDrawing,60)
		else
			BlzSetSpecialEffectColor(mainData.effDrawing,255,0,0)
			BlzSetSpecialEffectAlpha(mainData.effDrawing,128)
		end

		if mainData.ReleaseLMB  then-- кнопка хажата
			starDrawing=true
			lastDistance = lastDistance + distanceMove
		else
			if starDrawing or mainData.DestroyDrawing then
				if DestroyEatingCactus(mainData,data,true) then
					CreateCactus(mainData, x, y, r,curAngle)
				end

				return
			end
		end
		if lastDistance > range then
			DestroyEatingCactus(mainData,data,false)

			if CustomAbilityIsReady(mainData,data) then
				EatingCactus(mainData)
			end

			if lastDistance>range*2 then
				local int = R2I(lastDistance / range)
				for i = 0, int do
					local angle = AngleBetweenXY(lastX, lastY, xp, yp) / bj_DEGTORAD
					--print(angle)
					r = GetRandomInt(0, 9)
					local nx, ny = MoveXY(lastX, lastY, range * i, angle)
					--AddSpecialEffect(cactusModel..r,nx,ny)
					CreateCactus(mainData, nx, ny, r,angle)
					--print("рисуем недостающие кактусы "..i)
				end
			else
				CreateCactus(mainData, x, y, r,curAngle)
			end
		end
		lastX, lastY = x, y
		local z = GetTerrainZ(x, y)
		if mainData.effDrawing then
			BlzSetSpecialEffectPosition(mainData.effDrawing, x, y, z)
			BlzSetSpecialEffectYaw(mainData.effDrawing, math.rad(curAngle))
		end
	end)
end

function CreateCactus(mainData, x, y, r,angle)
	local eff=nil
	local timeLife = CreateTimer()
	local data=mainData.FrameTable[11]
	if data.Charges>0 then
		if IsPointCanCreatedCactus(mainData, x, y) then
			data.Charges=data.Charges-1
			eff = AddSpecialEffect(cactusModel .. r, x, y)
			BlzSetSpecialEffectYaw(eff, math.rad(angle))
		end
	else
		mainData.ReleaseLMB=false
		mainData.DestroyDrawing=true
		--print("Зарядов больше нет")
	end

	TimerStart(timeLife, TIMER_PERIOD, true, function()
		-- урон и отталкивание
		--Кактус пикает группу вокруг себя
		local e=nil
		GroupEnumUnitsInRange(perebor,x,y,80,nil)
		while true do
			e = FirstOfGroup(perebor)

			if e == nil then break end
			if UnitAlive(e) and IsUnitEnemy(e,GetOwningPlayer(mainData.UnitHero)) then
				local angleBU=AngleBetweenXY(x,y,GetUnitXY(e))/ bj_DEGTORAD
				if onForces[GetHandleId(e)] or onForces[GetHandleId(e)]==nil then
					--print("урон?")
					UnitDamageTarget( mainData.UnitHero, e, 20, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS )
				end
				UnitAddForceSimple(e,angleBU,30,180)
			end
			GroupRemoveUnit(perebor,e)
		end

	end)
	TimerStart(CreateTimer(), 10, false, function()
		DestroyTimer(GetExpiredTimer())
		DestroyTimer(timeLife)
		BlzSetSpecialEffectPosition(eff, OutPoint, OutPoint, 0)
		DestroyEffect(eff)
	end)
end

function IsPointCanCreatedCactus(mainData,x,y)
	return not (IsTerrainPathable(x, y,PATHING_TYPE_WALKABILITY)
			or not IsVisibleToPlayer(x, y,GetOwningPlayer(mainData.UnitHero))
			or DistanceBetweenXY(x,y,GetUnitXY(mainData.UnitHero))>=1000
	)
end