---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 20.04.2021 23:38
---
function CreateABSQuest()
    local id = FourCC("h001")
    local _, _, unitTable = FindUnitOfType(id)
    local k = #unitTable
    --print(k)
    TypeWord = ""
    local abs = {
        "x",
        "g",
        "m",
        "e",
        "a",
        "l",
        "y",
        "h",
    }
    local r = GetRandomIntTable(1, #abs, #abs)

    for i = 1, k do
        local u = unitTable[i]
        SetUnitOwner(u, Player(PLAYER_NEUTRAL_PASSIVE), true)
        local x, y = GetUnitXY(u)
        SetUnitInvulnerable(u, true)
        CreateEnterPoint(x, y, L("Писать", "Write"), 'Write' .. abs[r[i]], true)
    end
end

function Type(type)
    TypeWord = TypeWord .. type
    print(TypeWord)
    local x, y = GetUnitXY(GetRandomEnemyHero())
    if not WordReward then
        if TypeWord == "XGM" then
            print("посхалка XGM")
            CreateGodTalon(x, y, "CodoHeart")
            TypeWord = ""
            WordReward = true
        end
        if TypeWord == "HELGA" then
            print("Кто такая Хельга?")
            CreateGodTalon(x, y, "Life")
            TypeWord = ""
            WordReward = true
        end
        if TypeWord == "HELL" then
            print("Ад?? я не хотел это писать, это ошибка")
            TypeWord = ""
            StartEnemyWave(45)
            WordReward = true
        end
        if TypeWord == "GYM" then
            print("Время потренировать мышцы")
            CreateGodTalon(x, y, "PeonDidal")
            TypeWord = ""
            WordReward = true
        end
    end
    if #TypeWord >= 5 then
        TypeWord = ""
        --print("очистка")
        CreateCreepDelay(FourCC("uban"), x, y, 2, "summon")
    end
    return #TypeWord
end