---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 17.02.2021 16:07
---

do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), 2, false, function()
            ReplaceALLUnitId2PointExit(FourCC("hdhw"))
            CreateEActions()
            InitFinObjectInArea()
            AllActionsEnabled(true)
        end)
    end
end

ActionList = {}
ActionListIndex = 1
PreViewIcon = { -- Таблица случайных иконок которые могу быть дарами, установлены у входа
    --"HeroArchMage",
    --"HeroBloodElfPrince",
    --"HeroMountainKing",
    --"HeroPaladin",
    "HeroBlademaster",
    "HeroTaurenChieftain",
    "ShadowHunter",
    "Trall",
    "CodoHeart",
    "GoldReward"
}

function InitFinObjectInArea()
    CreateEnterPoint(5300, -9000, "   Подняться на борт", "StartSheep", true)--зона корабля
    CreateEnterPoint(2100,-13250,"      Выйти наружу", "ExitSheep", true )
    CreateEnterPoint(5400, -8300, "   Исследовать лодку", "Board", true) --Левая лодка
    CreateEnterPoint(5500, -6900, "  Войти", "BackDor", true) --Вечно закрытые ворота
    CreateEnterPoint(7700, -8000, "     Преисполниться", "StartBonus", true) --Синий огонь
    CreateEnterPoint(7800, -6600, "    Посмотреть вдаль", "SoFar", true) --на краю берега справа
    CreateEnterPoint(7000, -9200, "        Рыбачить", "Fish", true) -- внизу на берегу
    CreateEnterPoint(7200, -7600, "       Отдохноуть", "NoWorking", true) -- возле деревьев
    --[[
    --Переходы между зонами
    FinObjectInArea(6600, -6300, "Войти через главный вход", "Goto", true, "Trall") --Начать приключение
    FinObjectInArea(14710, -11735, "        Продолжить", "Goto", false)
    FinObjectInArea(15665, -12743, "        Продолжить", "Goto", false)
    FinObjectInArea(18545, -12487, "        Продолжить", "Goto", false)
    FinObjectInArea(12913, -8415, "        Продолжить", "Goto", false)
    FinObjectInArea(13940, -8415, "        Продолжить", "Goto", false)

    FinObjectInArea(15089, -5911, "        Продолжить", "Goto", false)
    FinObjectInArea(16338, -6629, "        Продолжить", "Goto", false)
    FinObjectInArea(18036, -10000, "       Продолжить", "Goto", false)
    FinObjectInArea(18931, -10000, "        Продолжить", "Goto", false)
    FinObjectInArea(19442, -6286, "        Продолжить", "Goto", false)
    FinObjectInArea(20214, -7145, "        Продолжить", "Goto", false)
    ]]
    --FinObjectInArea(0,-0,"   Продолжить","Goto",false)
end


function ReplaceALLUnitId2PointExit(id)
    local _,_,unitTable=FindUnitOfType(id)
    local k=#unitTable
    print(k)
    for i=1,k do
        local u=unitTable[i]
        local x,y=GetUnitXY(u)
        SetUnitInvulnerable(u,true)
        --UnitAddAbility(u,FourCC("Aloc"))
        --ShowUnit(u,false)
        CreateEnterPoint(x,y,"        Продолжить", 'Goto', false,nil,u)
    end
end

EnterPointTable={}

function CreateEnterPoint(x,y,message, actionFlag, isActive, reward,tempUnit)
    if not tempUnit then
        --print("юнит не определён, создаём "..actionFlag)
        tempUnit=CreateUnit(Player(PLAYER_NEUTRAL_PASSIVE), FourCC("hdhw"),x,y,0)
        SetUnitInvulnerable(tempUnit,true)
        --UnitAddAbility(tempUnit,FourCC("Aloc"))
    end
    EnterPointTable[GetHandleId(tempUnit)]={}
    local dataPoint=EnterPointTable[GetHandleId(tempUnit)]
    if not reward then
        reward = PreViewIcon[GetRandomInt(1, #PreViewIcon)]
    end
    local preView = nil
    if actionFlag == "Goto" then
        preView = AddSpecialEffect("SystemGeneric\\GodModels\\" .. reward, x, y)
        BlzSetSpecialEffectYaw(preView, math.rad(90))
        BlzSetSpecialEffectScale(preView, 2)
        --print(" Лист действий"..ActionListIndex.." награда записана "..reward) -- эта строчка точно верная 100
        --GLOBAL_REWARD=reward


    end
    ActionList[ActionListIndex] = {
        x = x,
        y = y,
        actionFlag = actionFlag,
        reward = reward
    }

    ActionListIndex = ActionListIndex + 1
    local activeNumber = ActionListIndex - 1
    --local range = 200
    --local rect = Rect(x - range, y - range, x + range, y + range)
    local tooltip, backdrop, text = CreateActionBox(message)

    ActionList[activeNumber].isActive = isActive
    ActionList[activeNumber].self=dataPoint
    dataPoint.tooltip=tooltip
    dataPoint.UseAction = actionFlag
    dataPoint.isActive=isActive
    dataPoint.CurrentReward=reward
    dataPoint.preView=preView

    if actionFlag == "Goto" then
        local _,k,tempTable=FindUnitOfType(FourCC("hdhw"),1500,x,y)
        if k>=2 then
            for i=1,k do
                local dataPoint2=EnterPointTable[GetHandleId(tempTable[i])]
                if dataPoint2 then
                    if dataPoint2.CurrentReward==reward and tempTable[i]~=tempUnit then
                        local temTableReward=PreViewIcon
                        table.remove(temTableReward,FinPosInTable(temTableReward,reward))
                        local newReward = temTableReward[GetRandomInt(1, #temTableReward)]
                        DestroyEffect(dataPoint.preView)
                        dataPoint.CurrentReward=newReward

                        preView = AddSpecialEffect("SystemGeneric\\GodModels\\" .. newReward, x, y)
                        BlzSetSpecialEffectYaw(preView, math.rad(90))
                        BlzSetSpecialEffectScale(preView, 2)
                        dataPoint.preView=preView

                        --print("Найден дубликат дара "..reward.."заменяем его на "..newReward)
                        --AddSpecialEffect("SystemGeneric\\LightPillar", x, y)
                    end
                end
            end
        end
    end
end
function FinPosInTable(t,f)
    local pos=0
    for i=1,#t do
        if t[i]==f then
            pos=i
            return pos
        end
    end
    --print(pos)
    return pos
end



function AllActionsEnabled(enable)
    for i = 1, #ActionList do
        if ActionList[i].actionFlag == "Goto" then
            local dataPoint=ActionList[i].self
            dataPoint.isActive=enable
            ActionList[i].isActive = enable
            if not enable then
               -- print("выходы заблокированы "..i)
            else
                --print("выходы разблокированы "..i)
            end
        end
    end
end



function FinObjectInAreaOLD(x, y, message, actionFlag, isActive, reward)

    if not reward then
        reward = PreViewIcon[GetRandomInt(1, #PreViewIcon)]
    end
    local preView = nil
    if actionFlag == "Goto" then
        preView = AddSpecialEffect("SystemGeneric\\GodModels\\" .. reward, x, y)
        BlzSetSpecialEffectYaw(preView, math.rad(90))
        BlzSetSpecialEffectScale(preView, 2)

        --print(" Лист действий"..ActionListIndex.." награда записана "..reward) -- эта строчка точно верная 100
        --GLOBAL_REWARD=reward
    end
    ActionList[ActionListIndex] = {
        x = x,
        y = y,
        actionFlag = actionFlag,
        reward = reward
    }

    ActionListIndex = ActionListIndex + 1
    local activeNumber = ActionListIndex - 1
    local thisTrigger = CreateTrigger()
    local thisTrigger2 = CreateTrigger()
    local range = 200
    local rect = Rect(x - range, y - range, x + range, y + range)
    local tooltip, backdrop, text = CreateActionBox(message)

    ActionList[activeNumber].isActive = isActive
    TriggerRegisterEnterRectSimple(thisTrigger, rect)
    TriggerAddAction(thisTrigger, function()
        local u = GetTriggerUnit()
        local pid = GetPlayerId(GetTriggerPlayer())
        if HERO[pid].UnitHero == u and ActionList[activeNumber].isActive then
            DisableTrigger(thisTrigger)
            --print(message)
            if not HERO[pid].DoAction then
                HERO[pid].DoAction = true
                HERO[pid].UseAction = actionFlag
                HERO[pid].CurrentReward = reward
                BlzFrameSetVisible(tooltip, GetLocalPlayer() == GetOwningPlayer(GetTriggerUnit()))
            end
            TimerStart(CreateTimer(), 0.1, false, function()
                EnableTrigger(thisTrigger)
            end)
            TimerStart(CreateTimer(), 0.5, true, function()
                --таймер ожидания
                if not HERO[pid].DoAction then
                    DestroyTimer(GetExpiredTimer())
                    if HERO[pid].Completed then
                        HERO[pid].Completed = false
                        ActionList[activeNumber].isActive = false
                    end
                    if GetLocalPlayer() == GetOwningPlayer(u) then
                        BlzFrameSetVisible(tooltip, false)
                    end
                    --print("вышел из зоны, таймер отлова клавиши больше не нужен")
                end
            end)
        end
    end)
    TriggerRegisterLeaveRectSimple(thisTrigger2, rect) --выход из зоы
    TriggerAddAction(thisTrigger2, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local u = GetTriggerUnit()
        if HERO[pid].UnitHero == u and ActionList[activeNumber].isActive then
            DisableTrigger(thisTrigger2)
            if HERO[pid].DoAction then
                HERO[pid].DoAction = false
                HERO[pid].UseAction = ""
                if GetLocalPlayer() == GetOwningPlayer(u) then
                    BlzFrameSetVisible(tooltip, false)
                end
            end
            --print(message)
            TimerStart(CreateTimer(), 0.1, false, function()
                EnableTrigger(thisTrigger2)
            end)
        end
    end)
    --return
end

function CreateActionBox(message)
    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "StandardFrameTemplate", 0)
    local backdrop = BlzCreateFrame("QuestButtonDisabledBackdropTemplate", tooltip, 0, 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
    local size = #message * 0.0045
    if size <= 0.1 then
        size = 0.1
    end
    BlzFrameSetAbsPoint(tooltip, FRAMEPOINT_CENTER, 0.4, 0.08)
    BlzFrameSetSize(tooltip, 0.2, 0.04)
    BlzFrameSetSize(backdrop, size, 0.04)
    BlzFrameSetPoint(backdrop, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
    BlzFrameSetAlpha(backdrop, 200)
    BlzFrameSetText(text, message)
    BlzFrameSetScale(text, 1.2)
    BlzFrameSetPoint(text, FRAMEPOINT_RIGHT, backdrop, FRAMEPOINT_RIGHT, -0.01, 0.0)
    BlzFrameSetVisible(tooltip, false)
    local hotkey = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', tooltip, '', 0)
    BlzFrameSetTexture(hotkey, "SystemGeneric\\HadesE", 0, true)
    BlzFrameSetSize(hotkey, NextPoint, NextPoint)
    BlzFrameSetPoint(hotkey, FRAMEPOINT_LEFT, backdrop, FRAMEPOINT_LEFT, 0.01, 0.0)
    return tooltip, backdrop, text, hotkey
end

function CreateEActions()
    -----------------------------------------------------------------OSKEY_E
    local gg_trg_EventUpE = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpE, Player(i), OSKEY_E, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpE, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseE and UnitAlive(data.UnitHero) then
            data.ReleaseE = true
            --print("e is pressed")
            --ТУТ ПЕРЕЧИСЛЯЕМ ДЕЙСТВИЯ ЧЕРЕЗ ИФ
            if data.UseAction == "StartSheep" then
                local message = "Кто-то убрал трап, я не могу подняться сейчас на борт"
                CreateInfoBoxForAllPlayerTimed(data, message, 5)
                data.Completed = true
                data.DoAction = false
                data.UseAction = ""
                if false then
                    local x,y=1750,-12500 --2100,-13250 На выход
                    SetUnitPositionSmooth(data.UnitHero,x,y)
                end
            end

            if data.UseAction == "ExitSheep" then
                local message = "На свежий воздух"
                CreateInfoBoxForAllPlayerTimed(data, message, 5)
                data.Completed = true
                data.DoAction = false
                data.UseAction = ""
                if true then
                    local x,y=5300, -9000 --2100,-13250 На выход
                    SetUnitPositionSmooth(data.UnitHero,x,y)
                end
            end

            if data.UseAction == "Board" then
                local message = "Здесь ничего нет"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                data.DoAction = false
                data.UseAction = ""
            end
            if data.UseAction == "BackDor" then
                local message = "Даже не похоже, что эту дверь можно открыть снаружи"
                CreateInfoBoxForAllPlayerTimed(data, message, 4)
                data.DoAction = false
                data.UseAction = ""
            end
            -----------------------------------------------------
            -----------------------------------------------------
            -----------------------------------------------------
            if data.UseAction == "Goto" then
                local rm = {
                    "Что нас ждём внутри?",
                    "Надеюсь, что будет полегче",
                    "Откройся, Сезам",
                    "А что же там?"
                }
                local r = GetRandomInt(1, #rm)
                local message = rm[r]
                CreateInfoBoxForAllPlayerTimed(data, message, 3)

                --GLOBAL_REWARD = data.CurrentReward
                Enter2NewZone()
                DestroyDecorInArea(data, 300)
                --print("звук открытия ворот")
                normal_sound("Sound\\Interface\\BattlenetBirth1",GetUnitXY(data.UnitHero))
                data.Completed = true
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
                local dataPoint=EnterPointTable[GetHandleId(data.EPointUnit)]
                --print("переходим в зону с этой наградой "..dataPoint.CurrentReward)
                GLOBAL_REWARD=dataPoint.CurrentReward
                AllActionsEnabled(false)-- блокируем все новые переходы
            end
            if data.UseAction == "StartBonus" then
                local message1 = "Я в своём познании настолько преисполнился, что как будто бы уже 100"
                local message2 = "триллионов миллиардов лет проживаю на триллионах и триллионах таких же планет"
                CreateInfoBoxForAllPlayerTimed(data, message2, 10)
                CreateInfoBoxForAllPlayerTimed(data, message1, 10)
                data.Completed = true
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
                CreateGodTalon(GetUnitX(data.EPointUnit),GetUnitY(data.EPointUnit), "PeonDidal")
            end
            if data.UseAction == "SoFar" then
                local message = "Ничего не видно без оптического прибора"
                CreateInfoBoxForAllPlayerTimed(data, message, 5)
                data.Completed = true
                data.DoAction = false
                data.UseAction = ""
            end
            if data.UseAction == "Fish" then
                local message = "Руками, без удочки"
                CreateInfoBoxForAllPlayerTimed(data, message, 5)
                data.Completed = true
                data.DoAction = false
                data.UseAction = ""

            end
            if data.UseAction == "NoWorking" then
                local message = "Я здесь не для отдыха"
                CreateInfoBoxForAllPlayerTimed(data, message, 5)
                data.Completed = true
                data.DoAction = false
                data.UseAction = ""
            end
            ----------------------------------------------------/
            ---------------ДАРЫ БОГОВ---------------------------/
            ----------------------------------------------------/
            if data.UseAction == "Trall" then
                local message = "Провидец, я выбираю тебя"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                AllActionsEnabled(true)--активация всех переходов
                TimerStart(CreateTimer(), 1, false, function()
                    --print("Создаём диалоговое окно для всех игроков Jsore")
                    CreateDialogTalon("Trall") -- Сюда передаётся trall
                    DestroyGodTalon(LastGodTalon)
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
                --GetTerrainZ()
            end
            if data.UseAction == "HeroBlademaster" then
                local message = "Надели меня силой своего клинка"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                AllActionsEnabled(true)
                TimerStart(CreateTimer(), 1, false, function()
                    DestroyGodTalon(LastGodTalon)
                    CreateDialogTalon("HeroBlademaster")
                    --активация всех переходов
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
            end
            if data.UseAction == "HeroTaurenChieftain" then
                local message = "Держите оборону"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                AllActionsEnabled(true)
                TimerStart(CreateTimer(), 1, false, function()
                    DestroyGodTalon(LastGodTalon)
                    CreateDialogTalon("HeroTaurenChieftain")
                    --активация всех переходов
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
            end
            if data.UseAction == "ShadowHunter" then
                local message = "Я отомщю за тебя"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                AllActionsEnabled(true)
                TimerStart(CreateTimer(), 1, false, function()
                    DestroyGodTalon(LastGodTalon)
                    CreateDialogTalon("ShadowHunter")
                    --активация всех переходов
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
            end
            if data.UseAction == "HeroArchMage" then
                local message = "Гендальф белый"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                AllActionsEnabled(true)
                TimerStart(CreateTimer(), 1, false, function()
                    DestroyGodTalon(LastGodTalon)
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
            end
            if data.UseAction == "HeroPaladin" then
                local message = "За твоего отца"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                AllActionsEnabled(true)
                TimerStart(CreateTimer(), 1, false, function()
                    DestroyGodTalon(LastGodTalon)
                    --активация всех переходов
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
            end
            if data.UseAction == "HeroBloodElfPrince" then
                local message = "Инвокер, ты ли это?"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                AllActionsEnabled(true)
                TimerStart(CreateTimer(), 1, false, function()
                    DestroyGodTalon(LastGodTalon)
                    --активация всех переходов
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
            end
            if data.UseAction == "HeroMountainKing" then
                local message = "Помоги мне подраться"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                TimerStart(CreateTimer(), 1, false, function()
                    DestroyGodTalon(LastGodTalon)
                    AllActionsEnabled(true)--активация всех переходов
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
            end
            if data.UseAction == "HeroBeastMaster" then
                local message = "Сила братьев"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                DestroyGodTalon(LastGodTalon)
                CreateDialogTalon("HeroBeastMaster")
                AllActionsEnabled(true)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
                --normal_sound("Abilities\\Spells\\Other\\Transmute\\AlchemistTransmuteDeath1",GetUnitXY(data.UnitHero))
            end
            ----------------------------------------------------/
            ---------------Прочие дары--------------------------/
            ----------------------------------------------------/
            if data.UseAction == "CodoHeart" then
                local message = "Сила кодоя"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                TimerStart(CreateTimer(), 1, false, function()
                    DestroyGodTalon(LastGodTalon)
                    AllActionsEnabled(true)--активация всех переходов
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
                GiveForAll("CodoHeart")
            end
            if data.UseAction == "GoldReward" then
                local message = "Звонкая монета"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                DestroyGodTalon(LastGodTalon)
                AllActionsEnabled(true)
                TimerStart(CreateTimer(), 1.6, false, function()
                    --активация всех переходов
                    GiveForAll("GoldReward" )
                end)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
                normal_sound("Abilities\\Spells\\Other\\Transmute\\AlchemistTransmuteDeath1",GetUnitXY(data.UnitHero))
            end

            if data.UseAction == "PeonDidal" then
                local message = "Сила братьев"
                CreateInfoBoxForAllPlayerTimed(data, message, 3)
                data.Completed = true
                DestroyGodTalon(LastGodTalon)
                CreateDialogTalon("PeonDidal")
                AllActionsEnabled(true)
                data.DoAction = false
                data.UseAction = ""
                KillUnit(data.EPointUnit)
                --normal_sound("Abilities\\Spells\\Other\\Transmute\\AlchemistTransmuteDeath1",GetUnitXY(data.UnitHero))
            end


        end
    end)
    local TrigDepressE = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressE, Player(i), OSKEY_E, 0, false)
    end
    TriggerAddAction(TrigDepressE, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseE = false
    end)
end

InfoSlots = 0
function CreateInfoBoxForAllPlayerTimed(data, message, timed)

    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "StandardFrameTemplate", 0)
    local backdrop = BlzCreateFrame("QuestButtonDisabledBackdropTemplate", tooltip, 0, 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
    local size = #message * 0.004
    if size <= 0.12 then
        size = 0.12
    end
    BlzFrameSetAbsPoint(tooltip, FRAMEPOINT_CENTER, 0.4, 0.16 + 0.03 * InfoSlots)
    BlzFrameSetSize(tooltip, 0.2, 0.04)
    BlzFrameSetSize(backdrop, size, 0.03)
    BlzFrameSetPoint(backdrop, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
    BlzFrameSetAlpha(backdrop, 220)
    BlzFrameSetText(text, message)
    BlzFrameSetScale(text, 1.2)
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, backdrop, FRAMEPOINT_CENTER, 0, 0.0)
    --BlzFrameSetVisible(tooltip,true)
    TimerStart(CreateTimer(), timed, false, function()
        BlzFrameSetVisible(tooltip, true)
        BlzDestroyFrame(tooltip)
        InfoSlots = InfoSlots - 1
    end)
    InfoSlots = InfoSlots + 1
end


function DestroyDecorInArea(data, range)
    local x, y = GetUnitXY(data.UnitHero)
    SetRect(GlobalRect, x - range, y - range, x + range, y + range)
    EnumDestructablesInRect(GlobalRect, nil, function()
        KillDestructable(GetEnumDestructable())
    end)
end
