---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 08.05.2021 12:01
---
---
ChaosRollCost=10
function CreateActionsG()
    -----------------------------------------------------------------OSKEY_G
    local gg_trg_EventUpG = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpG, Player(i), OSKEY_G, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpG, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]

        local tableRandom1 = {
            "HeroBlademaster",
            "HeroTaurenChieftain",
            "ShadowHunter",
            "Trall",
            "ChaosGrom",
            "Alchemist",
            "HeroMountainKing",
            "Cheese"
        }
        local tableRandom2 = {
            "Life",
            "CodoHeart",
            "GoldReward",
            "Cheese"
        }

        if not data.ReleaseG and UnitAlive(data.UnitHero) then
            data.ReleaseG = true
            local dataPoint = EnterPointTable[GetHandleId(data.EPointUnit)]
            if data.CanPressG and data.chaosPoint>= ChaosRollCost then
                if dataPoint.CurrentReward == "PeonDidal" or dataPoint.CurrentReward == "Merchant" then
                    print("Смена награды невозможна")
                else
                    local test, newReward = GetAnyInTable(tableRandom2, dataPoint.CurrentReward)
                    if not test then
                        test, newReward = GetAnyInTable(tableRandom1, dataPoint.CurrentReward)
                    end
                    --print("нажата G, пробуем сменить талант с", dataPoint.CurrentReward, "на", newReward)
                    AddChaos(data, -ChaosRollCost)
                    ChangeGotoPoint(dataPoint, newReward)
                end

            end
        end
    end)
    local TrigDepressG = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressG, Player(i), OSKEY_G, 0, false)
    end
    TriggerAddAction(TrigDepressG, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseG = false
    end)
end

function ChangeGotoPoint(dataPoint, newReward)
    local x,y=GetUnitXY(dataPoint.Unit)
    DestroyEffect(dataPoint.preView)
    dataPoint.CurrentReward = newReward
    local preView = AddSpecialEffect("SystemGeneric\\GodModels\\" .. newReward, x, y)
    BlzSetSpecialEffectYaw(preView, math.rad(90))
    BlzSetSpecialEffectScale(preView, 2)
    dataPoint.preView = preView
    dataPoint.OriginalModel = "SystemGeneric\\GodModels\\" .. newReward
end

function GetAnyInTable(sort, element)
    local is, any = nil, nil
    for i = 1, #sort do
        if sort[i] == element then
            -- print("Элемент",element,"содержится в этой таблице")
            is = true
            table.remove(sort, FinPosInTable(sort, element))
        end
    end
    any = sort[GetRandomInt(1, #sort)]
    --print("вернул",any)
    return is, any
end