---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 09.03.2021 2:43
---
function CreateMerchantAndGoods(x,y)
    local table={
        "HeroBlademaster",
        "HeroTaurenChieftain",
        "ShadowHunter",
        "Trall",
    }

    CreateGodTalon(x,y+(200),"CodoHeart",GetRandomInt(75,100))
    CreateGodTalon(x,y-(200),"PeonDidal",GetRandomInt(175,225))
    CreateGodTalon(x+200,y,table[GetRandomInt(1,#table)],GetRandomInt(125,150))
    CreateGodTalon(x-200,y,table[GetRandomInt(1,#table)],GetRandomInt(125,150))
end