---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.02.2021 18:37
---
do
    TimerStart(CreateTimer(), 2, false, function()
        InitAllZones()
        CurrentGameZone=0
    end)
end
GameZone={
    recEnter=nil,
    rectBound=nil,
    rectSpawn=nil,
    reward=nil
}
function InitAllZones()
    SetZone(1,gg_rct_E1A,gg_rct_B1A,gg_rct_S1A)
    SetZone(2,gg_rct_E2A,gg_rct_B2A,gg_rct_S2A)
    SetZone(3,gg_rct_E3A,gg_rct_B3A,gg_rct_S3A)
    SetZone(4,gg_rct_E4A,gg_rct_B4A,gg_rct_S4A)
    SetZone(5,gg_rct_E5A,gg_rct_B5A,gg_rct_S5A)
    SetZone(6,gg_rct_E6A,gg_rct_B6A,gg_rct_S6A)
    --SetZone(4,gg_rct_E4A,gg_rct_B4A,gg_rct_S4A)
    Destiny=GetRandomIntTable(1, #GameZone, #GameZone) -- судьба и распределение порядка игровых зон
    DestinyEnemies=GetRandomIntTable(1, #GameZone, #GameZone)
    for i = 1, #Destiny do
        print(Destiny[i])
    end

end

function SetZone(number,recEnter,rectBound,rectSpawn)
    if recEnter and rectBound and rectSpawn then
        GameZone[number]={
            recEnter=recEnter,
            rectBound=rectBound,
            rectSpawn=rectSpawn
        }
    else
        --print("Ошибка, игровая зона №"..number.." ещё не создана в WE")
    end
end



function Enter2NewZone()
    CurrentGameZone=CurrentGameZone+1
    if CurrentGameZone==1 then
        --print("убираем обучение")
        DestroyAllLearHelpers()
    end
    --print(" вошел в зону .. "..CurrentGameZone.. " для судьбы это зона "..Destiny[CurrentGameZone].. " а награда то какая? наверное ")

    CinematicFadeBJ(bj_CINEFADETYPE_FADEOUT, 2.00, "ReplaceableTextures\\CameraMasks\\Black_mask.blp", 0, 0, 0, 0.00)
    TimerStart(CreateTimer(),3, false, function()
        --print("Перемещаемся в игровую зону "..CurrentGameZone)
        if Destiny[CurrentGameZone] then
            MoveAllHeroAndBound(GameZone[Destiny[CurrentGameZone]].recEnter,GameZone[Destiny[CurrentGameZone]].rectBound)
            --StartEnemyWave(Destiny[CurrentGameZone])
            --print("запускаем волну № ",DestinyEnemies[CurrentGameZone])

            --StartEnemyWave(DestinyEnemies[CurrentGameZone])
            StartEnemyWave(6)
        else
            print(CurrentGameZone.." -ая зона не существует, перемещение туда не возможно, обратитесь к атору карты")
        end
        CinematicFadeBJ(bj_CINEFADETYPE_FADEIN, 2.00, "ReplaceableTextures\\CameraMasks\\Black_mask.blp", 0, 0, 0, 0.00)
    end)
end

function GetRandomIntTable(min, max, count)
    local keys = {}
    local out  = {}
    if min == max then return { min } end
    if max < min then min, max = max, min end
    local limit = math.abs(max - min) + 1
    count       = count == nil and limit or math.min(limit, count)
    if limit <= count then
        local ints = {}
        for i = min, max do
            table.insert(ints, i)
        end
        for _ = 1, limit do
            table.insert(out, table.remove(ints, math.random(1, #ints)))
        end
        return out
    else
        while #out < count do
            local i = math.random(min, max)
            if keys[i] == nil then
                keys[i] = true
                table.insert(out, i)
            end
        end
        return out
    end
end

function MoveAllHeroAndBound(recEnter,rectBound)
    local x,y=GetRectCenterX(recEnter),GetRectCenterY(recEnter)
    local x2,y2=GetRectCenterX(rectBound),GetRectCenterY(rectBound)
    EnumDestructablesInRect(recEnter,nil,function()
        KillDestructable(GetEnumDestructable())
    end)
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        if IsPlayerSlotState(Player(i), PLAYER_SLOT_STATE_PLAYING) and GetPlayerController(Player(i))==MAP_CONTROL_USER then
            local data=HERO[i]
            SetCameraBoundsToRectForPlayerBJ(Player(i),rectBound)
            SetUnitPosition(data.UnitHero,x,y)
        end
    end
    --CreateGodTalon(x2,y2,"Trall",80,80,255)
end

function StartEnemyWave(waveNumber)
    local listID={}
    local maxOnWave=1
    if waveNumber==1 then
        listID={  -- скелетов по 5
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
        }
        maxOnWave=5
    end

    if waveNumber==2 then
        listID={  -- скелетов по 5
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
        }
        maxOnWave=2
    end
    if waveNumber==3 then
        listID={  -- скелетов по 5
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
            FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
            --FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
            --FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),FourCC("nsko"),
        }
        maxOnWave=10
    end

    if waveNumber==4 then
        listID={  -- Очень много жуков
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
            FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),FourCC("ucs1"),
        }
        maxOnWave=10
    end

    if waveNumber==6 then
        listID={  -- некроманты
            FourCC("unec"),FourCC("unec"),FourCC("unec"),FourCC("unec"),FourCC("unec"),
            FourCC("unec"),FourCC("unec"),FourCC("unec"),FourCC("unec"),FourCC("unec"),
        }
        maxOnWave=5
    end

    if waveNumber==5 then
        listID={  -- Пуджи
            FourCC("uabo"),FourCC("uabo"),FourCC("uabo"),
            FourCC("uabo"),FourCC("uabo"),FourCC("uabo"),
            FourCC("uabo"),FourCC("uabo"),FourCC("uabo"),
            FourCC("uabo"),FourCC("uabo"),FourCC("uabo"),
        }
        maxOnWave=3
    end


    if listID[1] then
        StartWave(GameZone[Destiny[CurrentGameZone]].rectSpawn,listID,maxOnWave)
    else
        listID={FourCC("nsko")}
        StartWave(GameZone[Destiny[CurrentGameZone]].rectSpawn,listID,1)
        print("В волне врагов, нет ни одного ID, так и задумано?")
    end
end

LiveOnWave=0-- живые на волне
CurrentOnWave=0
function StartWave(rect,listID,max)
    -- print("start wave "..max)
    local MaxOnWave=#listID
    LiveOnWave=0
    --CurrentOnWave=max
    local k=1
    --print(0)
    for i = 1, max do
        local loc=GetRandomLocInRect(rect)
        local x,y=GetLocationX(loc),GetLocationY(loc)
        CreateCreepDelay(listID[k],x,y,0.9,k)
        --MaxOnWave=MaxOnWave-1
        k=k+1
    end
    TimerStart(CreateTimer(),1, true, function()
        if LiveOnWave<max-1 and k<=MaxOnWave then
            --print("убит из пачки, создаём "..k)
            local loc=GetRandomLocInRect(rect)
            local x,y=GetLocationX(loc),GetLocationY(loc)
            CreateCreepDelay(listID[k],x,y,1.5,k)
            k=k+1
        end
        if LiveOnWave<=0 and k>=max then
            --print("все убиты даём награду")
            local x,y=GetRectCenterX(rect),GetRectCenterY(rect)--GetUnitXY(HERO[0].UnitHero)
            --print()
            ---print(Destiny[CurrentGameZone].." выдёргивает талант из этой зоны. Создан "..ActionList[Destiny[CurrentGameZone]].reward)

            CreateGodTalon(x,y,GLOBAL_REWARD,80,80,255)
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function CreateCreepDelay(id,x,y,delay)
    local eff=AddSpecialEffect("Hive\\Magic CirclePentagram\\Magic CirclePentagram Fire\\MagicCircle_Fire.mdl",x,y)
    LiveOnWave=LiveOnWave+1
    TimerStart(CreateTimer(),delay, false, function()
        --print("create new")
        local new=CreateUnit(Player(10),id,x,y,GetRandomInt(0,360))

        DestroyEffect(eff)
        TimerStart(CreateTimer(),delay, true, function()
            if not UnitAlive(new) then
                DestroyTimer(GetExpiredTimer())
                LiveOnWave=LiveOnWave-1
                --print(LiveOnWave[k])
            end
        end)
    end)
end

