---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.02.2021 18:37
---
do
    TimerStart(CreateTimer(), 2, false, function()
        InitAllZones()
        CurrentGameZone=0
    end)
end
GameZone={
    recEnter=nil,
    rectBound=nil,
    rectSpawn=nil
}
function InitAllZones()
    SetZone(1,gg_rct_E1A,gg_rct_B1A,gg_rct_S1A)
    --SetZone(2,gg_rct_E2A,gg_rct_B2A,gg_rct_S2A)
    --SetZone(3,gg_rct_E3A,gg_rct_B3A,gg_rct_S3A)
    --SetZone(4,gg_rct_E4A,gg_rct_B4A,gg_rct_S4A)
    Destiny=GetRandomIntTable(1, #GameZone, #GameZone) -- судьба и распределение порядка игровых зон

    for i = 1, #Destiny do
        print(Destiny[i])
    end

end

function SetZone(number,recEnter,rectBound,rectSpawn)
    if recEnter and rectBound and rectSpawn then
        GameZone[number]={
            recEnter=recEnter,
            rectBound=rectBound,
            rectSpawn=rectSpawn
        }
    else
        --print("Ошибка, игровая зона №"..number.." ещё не создана в WE")
    end
end


function Enter2NewZone()
    CurrentGameZone=CurrentGameZone+1
    if CurrentGameZone==1 then
        print("убираем обучение")
    end
    CinematicFadeBJ(bj_CINEFADETYPE_FADEOUT, 1.00, "ReplaceableTextures\\CameraMasks\\Black_mask.blp", 0, 0, 0, 0.00)
    TimerStart(CreateTimer(),2, false, function()
        --print("Перемещаемся в игровую зону "..CurrentGameZone)
        MoveAllHeroAndBound(GameZone[Destiny[CurrentGameZone]].recEnter,GameZone[Destiny[CurrentGameZone]].rectBound)
        CinematicFadeBJ(bj_CINEFADETYPE_FADEIN, 1.00, "ReplaceableTextures\\CameraMasks\\Black_mask.blp", 0, 0, 0, 0.00)
    end)
end

function GetRandomIntTable(min, max, count)
    local keys = {}
    local out  = {}

    if min == max then return { min } end
    if max < min then min, max = max, min end
    local limit = math.abs(max - min) + 1
    count       = count == nil and limit or math.min(limit, count)
    if limit <= count then
        local ints = {}
        for i = min, max do
            table.insert(ints, i)
        end
        for _ = 1, limit do
            table.insert(out, table.remove(ints, math.random(1, #ints)))
        end
        return out
    else
        while #out < count do
            local i = math.random(min, max)
            if keys[i] == nil then
                keys[i] = true
                table.insert(out, i)
            end
        end
        return out
    end
end

function MoveAllHeroAndBound(recEnter,rectBound)
    local x,y=GetRectCenterX(recEnter),GetRectCenterY(recEnter)
    local x2,y2=GetRectCenterX(rectBound),GetRectCenterY(rectBound)
    EnumDestructablesInRect(recEnter,nil,function()
        KillDestructable(GetEnumDestructable())
    end)
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        if IsPlayerSlotState(Player(i), PLAYER_SLOT_STATE_PLAYING) and GetPlayerController(Player(i))==MAP_CONTROL_USER then
            local data=HERO[i]
            SetCameraBoundsToRectForPlayerBJ(Player(i),rectBound)
            SetUnitPosition(data.UnitHero,x,y)
        end
    end
    CreateGodTalon(x2,y2,"Trall",80,80,255)
end