---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.08.2020 0:58
---

do --Инициализация
	TimerStart(CreateTimer(), 0.2, false, function()
	--	ChangePointer()
	end)
end

function ChangePointer()
	local pointer=BlzFrameGetChild(BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0),13)
	--BlzFrameSetTexture(pointer, "UI\\Widgets\\tooltips\\Human\\tooltipmanaicon", 0, true)
	BlzFrameSetModel(pointer , "SystemGeneric\\selecter3.mdx", 0)
	local fakePointer=AddSpecialEffect("Attack",OutPoint,OutPoint)
	local lastX,lastY=GetPlayerMouseX[0],GetPlayerMouseY[0]
	local angleCast = AngleBetweenXY(lastX,lastY, GetPlayerMouseX[0],GetPlayerMouseY[0]) / bj_DEGTORAD
	local curAngle = angleCast
	local distance = DistanceBetweenXY(lastX,lastY, GetPlayerMouseX[0],GetPlayerMouseY[0])
	local cutDistance = distance
	local moving=0


	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		distance = DistanceBetweenXY(lastX,lastY, GetPlayerMouseX[0],GetPlayerMouseY[0])
		cutDistance = math.lerp(cutDistance, distance, TIMER_PERIOD * 16)
		angleCast = AngleBetweenXY(lastX,lastY, GetPlayerMouseX[0],GetPlayerMouseY[0]) / bj_DEGTORAD
		curAngle = lerpTheta(curAngle, angleCast, TIMER_PERIOD * 16)

		--print(cutDistance)
		--local xp, yp = GetPlayerMouseX[mainData.pid], GetPlayerMouseY[mainData.pid]
		local speed=cutDistance/5
		local x, y = MoveXY(GetPlayerMouseX[0],GetPlayerMouseY[0], speed, curAngle)
		--local distanceMove = DistanceBetweenXY(xp, yp, lastX, lastY)

		lastX, lastY = GetPlayerMouseX[0],GetPlayerMouseY[0]
		local z = GetTerrainZ(x, y)
		--BlzSetSpecialEffectPosition(mainData.effDrawing, x, y, z)
		if moving<=cutDistance then
			moving=moving+speed
			BlzSetSpecialEffectPosition(fakePointer,x,y,z)
		else
			moving=0
		--	print("перелёт")
		end

	end)



	--FrameSET
	BlzFrameSetAlpha(pointer,100)
	--print("mmm "..k)
end


function ForceMouse2Point(x,y,nx,ny)

	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		currentdistance = currentdistance + speed
		--print(currentdistance)
		local x, y = GetUnitX(hero), GetUnitY(hero)
		local newX, newY = MoveX(x, speed, angle), MoveY(y, speed, angle)

		SetUnitPositionSmooth(hero, newX, newY)

		if currentdistance >= distance then
			--or (data.OnWater and data.OnTorrent==false)
			--data.IsDisabled=false
			--data.OnWater=false
			DestroyTimer(GetExpiredTimer())
			onForces[GetHandleId(hero)]=true
			--print("stop cur="..currentdistance.." dist="..distance)
		end

	end)
end

