---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 09.03.2021 12:24
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), 1, false, function()
            InitLvlUp()
            DestroyTimer(GetExpiredTimer())
        end)
    end
end
function InitLvlUp()
    local this=CreateTrigger()
    TriggerRegisterAnyUnitEventBJ(this, EVENT_PLAYER_HERO_LEVEL)
    TriggerAddAction(this,function()
        --print("evnt")
        local hero=GetTriggerUnit()
        local data=HERO[GetPlayerId(GetOwningPlayer(hero))]
        if data.HealForLvlUp then
            --print("heal")
            local amount=BlzGetUnitMaxHP(hero)*data.HealForLvlUp/100
            HealUnit(hero,amount)
        end
    end)
end