---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05
--
---Глобалки
TIMER_PERIOD = 0.03125
HERO = {}
do
	local InitGlobalsOrigin = InitGlobals
	function InitGlobals()
		InitGlobalsOrigin()
		perebor = CreateGroup() --1 едиснвенная глобальная группа на всю игру, никакие Destroy Привет гуишники
		--InitSpellTrigger() -- Инициализация функции кастов
		InitHEROTable() -- Инициализация таблицы героев
		KeyRegistration() -- инициализация отлова нажатия клавиш
		InitSelectionRegister() -- инициализация выбора
		--print("пост инициализация выбора")
		InitMouseMoveTrigger() -- Запуск отслеживания положения мыши
		InitDamage()

		--InitSoundsA()--Создаём звуки
		--InitUnitDeath()-- инициализация смерти
		--CreateGlue()
		TimerStart(CreateTimer(), 0.1, false, function()

			InitMainFrameTable(HERO[0]) -- мульти создаётся здесь
			--print("заполнение таблицы таблицы")
		end)
	end
end

do
	-- Автоочистка таймеров
	local DestroyTimer_Original = DestroyTimer
	function DestroyTimer(whichTimer)
		PauseTimer(whichTimer)
		DestroyTimer_Original(whichTimer)
	end

end

function InitHEROTable()
	EnableDragSelect(false, false)
	if BlzLoadTOCFile("Main.toc") then
	else
		print("ошибка загрузки toc")
	end
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		HERO[i] = {
			pid = i,
			UnitHero = nil,
			IsInterface = false,
			IsMainHeroOnHit = false,
			EvasionState=false,
			FirePillarState=false,
			StartDrawing=false,
			DestroyDrawing=false,
			effDrawing=nil,
			DrawingTimer=nil,
			CustomAbilities = { -- статичные данные, но менять можно и муи
				[1] = {
					Ready = true,
					CD=10,
					Name="Фазовый сдвиг".." (|cffffcc00".."Пассивная".."|r)",
					Description="При получении урона герой смещается между пространствами и избегает этого урона а также любого последующего в течении 0.5 сек. Атаки по герою уменьшают перезарядку способности на 1 секунду",
					SizeTooltip=7,
				},
				[2] = {
					Ready = true,
					CD=15,
					Name="Огненный столб".." (|cffffcc00".."W ‡ ‡".."|r)",
					Description="Выпускает поток огня впереди себя",
					SizeTooltip=4,
				},
				[3] = {
					Ready = true,
					CD=0.1,
					Name="Поле кактусов".." (|cffffcc00".."E".."|r)",
					Description="Сажает кактусы в указанной точке, сажайте кактусы по 1 или удерживайте левую кнопку мыши зажатой, для массовм посадки. Способность имеет 10 зарядов, перезарядка заряда - 7 секунд ",
					MaxCharges=999,
					ManaCost=10,
					SizeTooltip=9,
				},
				[4] = {
					Ready = true,
					CD=7,
					Name="Массовое вытягивание жизни".." (|cffffcc00".."R".."|r)",
					Description="Отманиает у врагов жизни и передаёт их герою, герой неуязвим во время действия способности, пока испытывает нехватку здоровья и не может вытянуть больше здоровья чем у него недостаёт. Способность может быть отменена. Длительность: 5",
					ManaCost=50,
					SizeTooltip=10,
				},
				[5] = {
					Ready = true,
					CD=20,
					Name="Критический удар".." (|cffffcc00".."Пассивная".."|r)",
					Description="Когда способность готова, герой наносит увеличенный 5 кратный урон следующим любым источником урона, атаки с руки уменьшают перезарядку на 1 секунду",
					SizeTooltip=7,
				},
				[6] = {
					Ready = true,
					CD=20,
					Name="Движение".." (|cffffcc00".."ПКМ".."|r)",
					Description="Отдаёт юниту приказ движения в указанную точку, со скорость ".."|cffffcc00".."ms".."|r",
					SizeTooltip=5,
					Updatable=true
				},
				[7] = {
					Ready = true,
					CD=20,
					Name="Стоп".." (|cffffcc00".."S".."|r)",
					Description="Прерывает все текущие действия",
					SizeTooltip=4,
					Updatable=true
				},
				[8] = {
					Ready = true,
					CD=20,
					Name="Удерживать позицию".." (|cffffcc00".."H".."|r)",
					Description="Закрепляет текущую позицию как постоянную, но юнит может продолжать атаковать врагов в зоне дальности атаки ".."|cffffcc00".."ar".."|r",
					SizeTooltip=6,
					Updatable=true
				},
				[9] = {
					Ready = true,
					CD=20,
					Name="Атака".." (|cffffcc00".."A".."|r)",
					Description="Атакует указанное существо или первое существо, что попадётся на пути. Сила атаки: ap, Скорость атаки: as",
					SizeTooltip=6,
					Updatable=true
				},
				D = {},
				F = {}
			},
			FrameTable = {},
			ReleaseQ=false,
			ReleaseW=false,
			ReleaseE=false,
			ReleaseR=false,
			ReleaseLMB=false,
			ReleaseRMB=false,
			ReleaseESC=false,
			ReleaseTAB=false,
		}
	end
end


function InitMainFrameTable(data)
	--	local frames={}
	local k = 0
	local k2 = 1
	local greed = 0.0045
	for i = 1, 12 do -- заполнение таблицы пустышек
		data.FrameTable[i] = {
			SelfFrame = nil, -- Основной фрейм
			IconFrame = nil, -- Его иконка
			CdIndicatorFrame = nil, -- Фрейм перезарядки
			ToolTip=nil, -- фрейм подскизки, общий
			ChargesFrame=nil, -- фрейм зарядов
			ChargesFrameText=nil, --Число зарядов
			Number = i, -- номер фрейма 1-12 сверху вниз слева направо
			PosX = 0, -- координаты на сетке
			PosY = 0,
			OnCD = false, -- на кд
			CurrentCDTime = 0,  --время кд
			Timer = nil, --???
			PercentAmount = 0, -- фрейм показывающий число процентов для перезарядки
			OnPaused = false, -- кд на паузе
			Full = 0, --???
			CurrentCD = 0, -- Кд фрейма в момент его старта
			MouseOnFrame = false, -- мышка на кнопке
			HotKeyPos=0, -- номер фрейма по порядку QWER
			Charges=0, -- число зарядов
		}
		local data2 = data.FrameTable[i] --заполенеие ячеек, не трогать никогда
		k = k + 1
		if k == 5 then
			k = 1
			k2 = k2 + 1
		end
		data2.PosX = 0.637 + ((NextPoint + greed) * (k - 1))
		data2.PosY = 0.113 - ((NextPoint + greed) * (k2 - 1))
	end
	return data.FrameTable
end