---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.03.2021 1:23
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        TimerStart(CreateTimer(), 1, false, function()
            InitPreloadStart()
            cache = InitGameCache("cache")
        end)
    end
end

function InitPreloadStart()
    --print("Start preload tester")
    --PreloadGenClear()
    SavePath = "save\\PeonRPG2.txt"
    Preloader(SavePath) --в этот момент данные записываются в имя способности, для каждого игрока свои данные
    local s = BlzGetAbilityTooltip(FourCC('Agyv'), 0) --переменная S хранит асинхронные данные
    --print("AAAAAAA "..s)

    --for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
    local i = 0
    TimerStart(CreateTimer(), 2.1, true, function()
        if IsPlayerSlotState(Player(i), PLAYER_SLOT_STATE_PLAYING) and GetPlayerController(Player(i)) == MAP_CONTROL_USER then
            local data = HERO[i]
            local restoreGold = 0
            --print("Обработка игрока " .. i)
            if #s > 10 then
                s = 0
            end

            --restoreGold = SyncString(Player(i), I2S(s)) -- ЭТА СТРОЧКА КРАШИТ ВАР

            if GetLocalPlayer()==Player(i) then
                restoreGold=s
            end
                print(GetPlayerName(Player(i)) .. " перенес золота из прошлой игры " .. R2I(restoreGold))
                UnitAddGold(data.UnitHero, R2I(restoreGold))

        end
        i=i+1
        if i>=bj_MAX_PLAYER_SLOTS - 1 then
            --print("Таймер сделал своё дело")
            DestroyTimer(GetExpiredTimer())
        end
    end)
end


function SyncString(p, val)
    if (GetLocalPlayer() == p) then
        StoreString(cache, "", "", val)
    end
    TriggerSyncStart()
    if (GetLocalPlayer() == p) then
        SyncStoredString(cache, "", "")
    end
    TriggerSleepAction(2) -- меньшнее   значение    вызывает    десинх
    TriggerSyncReady()
    return GetStoredString(cache, "", "")
end
--[[
function Trig_CameraSynh_Actions takes nothing returns nothing
player p = Player(0)
real x= 0
real y = 0
real syncx = 0
real syncy = 0
string xs, ys
if GetLocalPlayer()==p
xs = R2S(GetMouseTerrainX())
ys = R2S(GetMouseTerrainY())
x = S2R(xs)// перезапись через строковый тип
y = S2R(ys)// иначе нули
endif
syncx = SyncReal(p, x)
syncy = SyncReal(p, y)
CreateUnit(p, 'e009', syncx, syncy, 0)
endfunction]]