---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 11.03.2021 1:23
---
do
    local InitGlobalsOrigin = InitGlobals
    function InitGlobals()
        InitGlobalsOrigin()
        PreloadigLags()
        TimerStart(CreateTimer(), 3.5, false, function()
            InitTrig_SyncLoadDone()
            InitPreloadStart()
            DestroyTimer(GetExpiredTimer())
        end)
    end
end

function PreloadigLags()
    local temp = CreateUnit(Player(0), FourCC("uzig"), OutPoint, OutPoint, 0)
    KillUnit(temp)
    temp = CreateUnit(Player(0), FourCC("uabo"), OutPoint, OutPoint, 0)
    KillUnit(temp)
    temp = CreateUnit(Player(0), FourCC("u000"), OutPoint, OutPoint, 0)
    KillUnit(temp)
    temp = CreateUnit(Player(0), FourCC("unec"), OutPoint, OutPoint, 0)
    KillUnit(temp)
end

function InitPreloadStart()
    --print("Start preload tester")
    --PreloadGenClear()
    SavePath = "save\\PeonRPG2.txt"
    Preloader(SavePath) --в этот момент данные записываются в имя способности, для каждого игрока свои данные
    local s = BlzGetAbilityTooltip(FourCC('Agyv'), 0) --переменная S хранит асинхронные данные
    --print("AAAAAAA "..s)
    BlzSendSyncData("myprefix", s)
    --for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
    local i = 0
    TimerStart(CreateTimer(), .2, true, function()
        if PlayerIsPlaying[i] then
            local data = HERO[i]
            if not udg_LoadCode[i] then
                udg_LoadCode[i] = 50
                LoadedGameCount[i] = 0
                LoadedChaos[i] = 0
            end

            if udg_LoadCode[i] then
                if tonumber(LoadedGold[i]) then
                else
                    LoadedGold[i] = 50
                    LoadedGameCount[i] = 0
                    LoadedChaos[i] = 0
                    --print("FirstGame")
                end
                print(GetPlayerName(Player(i)) .. L(" Число завершенных игр ", " Number of completed games ") .. LoadedGameCount[i])
                LoadedGameCount[i] = LoadedGameCount[i] + 1
                if LoadedGameCount[i] > 2 then
                    AllCompletedForPlayer(i)
                end
                UnitAddGold(data.UnitHero, LoadedGold[i])
                AddChaos(data, LoadedChaos[i])
            else
                --i=i-1
            end
            --end)
        end
        i = i + 1
        if i >= bj_MAX_PLAYER_SLOTS - 1 then
            --print("Таймер сделал своё дело")
            DestroyTimer(GetExpiredTimer())
        end
    end)

end

udg_LoadCode = {}
LoadedGold = {}
LoadedGameCount = {}
LoadedChaos = {}
function InitTrig_SyncLoadDone ()
    local gg_trg_SyncLoadDone = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerSyncEvent(gg_trg_SyncLoadDone, Player(i), "myprefix", false)
    end
    TriggerAddAction(gg_trg_SyncLoadDone, function()
        local prefix = BlzGetTriggerSyncPrefix()
        local value = BlzGetTriggerSyncData()
        local i = GetPlayerId(GetTriggerPlayer())
        --print("SyncData="..value)
        if prefix == "myprefix" then
            local t = split(value, ",")-- разрезаем наталицу отдельныйх данных
            udg_LoadCode[i] = value
            LoadedGold[i] = t[1]
            LoadedGameCount[i] = t[2]
            LoadedChaos[i] = t[3]
            --print(t[2])
            if value == "error" then
                --игрок первый раз играет
                udg_LoadCode[i] = 0
                LoadedGold[i] = 0
                LoadedGameCount[i] = 0
                LoadedChaos[i] = 0
            end
            if not LoadedGameCount[i] then
                LoadedGameCount[i] = 0
            end
            if not LoadedChaos[i] then
                LoadedChaos[i] = 0
            end
            --print("udg_LoadCode"..i.."="..udg_LoadCode[i])
        end
    end)
end

function split(str, sep)
    if sep == nil then
        local words = {}
        for word in str:gmatch("%%w+") do
            table.insert(words, word)
        end
        return words
    end
    return { str:match((str:gsub("[^" .. sep .. "]*" .. sep, "([^" .. sep .. "]*)" .. sep))) } -- BUG!! doesnt return last value
end

function SaveResult(SaveCode)
    Preload("\")\ncall BlzSetAbilityTooltip ('Agyv',\"" .. SaveCode .. "\",0)" .. "\n//")
    PreloadGenEnd(SavePath)
    PreloadGenClear()
end

