---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 20.03.2021 19:38
---
function CreateTotemInLine(data)
    local hero = data.UnitHero
    local x, y = GetUnitXY(hero)
    local step = 60
    local dist = DistanceBetweenXY(GetPlayerMouseX[data.pid], GetPlayerMouseY[data.pid], GetUnitXY(hero))
    local angle = AngleBetweenXY(GetUnitX(hero), GetUnitY(hero), GetPlayerMouseX[data.pid], GetPlayerMouseY[data.pid]) / bj_DEGTORAD
    local maxBlock = dist // step
    --print("требуется блоков="..maxBlock)
    if maxBlock > 10 then
        maxBlock = 10
    end
    if maxBlock < 2 then
        maxBlock = 2
    end
    local i = 1
    TimerStart(CreateTimer(), 0.05, true, function()
        i = i + 1
        if data.TotemCharges > 0 then
            x, y = MoveXY(x, y, step, angle)
            data.TotemCharges = data.TotemCharges - 1
            BlzFrameSetText(data.TotemChargesFH, data.TotemCharges)
            CreateTotemElement(x, y, angle)
            UnitDamageArea(hero, 100, x, y, 150, "ForceTotem")
        else
            --break
        end
        if i >= maxBlock then
            DestroyTimer(GetExpiredTimer())
        end
    end)
end
function CreateTotemElement(x, y, angle)
    local collision = CreateDestructable(FourCC("B00A"), x, y, 0, 1, 1)
    local eff = AddSpecialEffect("units\\orc\\StasisTotem\\StasisTotem", x, y)
    local effStomp = AddSpecialEffect("Abilities\\Spells\\Human\\Polymorph\\PolyMorphDoneGround", x, y)
    DestroyEffect(effStomp)
    BlzSetSpecialEffectYaw(eff, math.rad(angle))
    TimerStart(CreateTimer(), 5, false, function()
        KillDestructable(collision)
        RemoveDestructable(collision)
        DestroyEffect(eff)
        DestroyTimer(GetExpiredTimer())
    end)
end
