---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.05.2021 20:32
---
function DestroyShieldArea(data,area,x,y)
    	local e=nil
			GroupEnumUnitsInRange(perebor,x,y,area,nil)
			while true do
				e = FirstOfGroup(perebor)

				if e == nil then break end
				if UnitAlive(e) and IsUnitHasShield(e) and IsUnitEnemy(e,GetOwningPlayer(data.UnitHero)) then
                    ShieldSystem[GetHandleId(e)].IsActive = false
                    SetUnitState(e,UNIT_STATE_MANA,0)
				end
				GroupRemoveUnit(perebor,e)
			end
end
