---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 14.02.2021 2:37
---

function SpellSlashQ(data)
    local hero=data.UnitHero
    if not data.tasks[3] then
        data.tasks[3]=true
    end
    local damage=250
    if data.GreatDamageDashQ then
        damage=2*damage
        data.GreatDamageDashQ=false
    end
        local x,y=MoveXY(GetUnitX(hero),GetUnitY(hero),80,GetUnitFacing(hero))
        DestroyEffect(AddSpecialEffect("SystemGeneric\\ThunderclapCasterClassic",x,y))
        UnitDamageArea(hero,damage,x,y,200)
end