---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.03.2021 13:38
---
function StartFrameCDWA (curCD, CdFH, talon, f)
    if curCD <= 0 then
        local cd = talon.DS[talon.level]
        curCD = cd
        StartFrameCD(cd, CdFH)
        f()
        TimerStart(CreateTimer(), cd, false, function()
            curCD = 0
            DestroyTimer(GetExpiredTimer())
        end)
    end
end

